# Generated by Django 3.2.3 on 2021-06-02 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], default='CREDIT', max_length=50)),
                ('transaction_status', models.CharField(choices=[('P', 'P'), ('I', 'I'), ('F', 'F'), ('S', 'S')], default='P', max_length=50)),
                ('transaction_reason', models.CharField(choices=[('Added money through bank', 'Added money through bank'), ('Added money through transfer by another user', 'Added money through transfer by another user'), ('Transaction was declined', 'Transaction was declined')], default='Added money through bank', max_length=200)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_by', to=settings.AUTH_USER_MODEL)),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
